

const citiesData = [
    { name: "Mumbai", state: "Maharashtra", country: "India" },
    { name: "Delhi", state: "Delhi", country: "India" },
    { name: "Bangalore", state: "Karnataka", country: "India" },
    { name: "Hyderabad", state: "Telangana", country: "India" },
    { name: "Chennai", state: "Tamil Nadu", country: "India" },
    { name: "Kolkata", state: "West Bengal", country: "India" },
    { name: "Ahmedabad", state: "Gujarat", country: "India" },
    { name: "Pune", state: "Maharashtra", country: "India" },
    { name: "Surat", state: "Gujarat", country: "India" },
    { name: "Jaipur", state: "Rajasthan", country: "India" },
    { name: "Lucknow", state: "Uttar Pradesh", country: "India" },
    { name: "Kanpur", state: "Uttar Pradesh", country: "India" },
    { name: "Nagpur", state: "Maharashtra", country: "India" },
    { name: "Indore", state: "Madhya Pradesh", country: "India" },
    { name: "Chandigarh", state: "Chandigarh", country: "India" },
    { name: "Coimbatore", state: "Tamil Nadu", country: "India" },
    { name: "Patna", state: "Bihar", country: "India" },
    { name: "Vadodara", state: "Gujarat", country: "India" },
    { name: "Bhopal", state: "Madhya Pradesh", country: "India" },
    { name: "Visakhapatnam", state: "Andhra Pradesh", country: "India" },
    { name: "Madurai", state: "Tamil Nadu", country: "India" },
    { name: "Faridabad", state: "Haryana", country: "India" },
    { name: "Ludhiana", state: "Punjab", country: "India" },
    { name: "Vijayawada", state: "Andhra Pradesh", country: "India" },
    { name: "Kochi", state: "Kerala", country: "India" },
    { name: "Mysuru", state: "Karnataka", country: "India" },
    { name: "Raipur", state: "Chhattisgarh", country: "India" },
    { name: "Agra", state: "Uttar Pradesh", country: "India" },
    { name: "Aurangabad", state: "Maharashtra", country: "India" },
    { name: "Nashik", state: "Maharashtra", country: "India" },
    { name: "Allahabad", state: "Uttar Pradesh", country: "India" },
    { name: "Dhanbad", state: "Jharkhand", country: "India" },
    { name: "Jabalpur", state: "Madhya Pradesh", country: "India" },
    { name: "Jammu", state: "Jammu and Kashmir", country: "India" },
    { name: "Howrah", state: "West Bengal", country: "India" },
    { name: "Ranchi", state: "Jharkhand", country: "India" },
    { name: "Guwahati", state: "Assam", country: "India" },
    { name: "Dehradun", state: "Uttarakhand", country: "India" },
    { name: "Kurnool", state: "Andhra Pradesh", country: "India" },
    { name: "Siliguri", state: "West Bengal", country: "India" },
    { name: "Bhubaneswar", state: "Odisha", country: "India" },
    { name: "Shivamogga", state: "Karnataka", country: "India" },
    { name: "Aligarh", state: "Uttar Pradesh", country: "India" },
    { name: "Meerut", state: "Uttar Pradesh", country: "India" },
    { name: "Chittoor", state: "Andhra Pradesh", country: "India" },
    { name: "Tumkur", state: "Karnataka", country: "India" },
    { name: "Bilaspur", state: "Chhattisgarh", country: "India" },
    { name: "Haridwar", state: "Uttarakhand", country: "India" },
    { name: "Gwalior", state: "Madhya Pradesh", country: "India" },
    { name: "Tirunelveli", state: "Tamil Nadu", country: "India" },
    { name: "Thane", state: "Maharashtra", country: "India" },
    { name: "Pondicherry", state: "Puducherry", country: "India" },
    { name: "Udaipur", state: "Rajasthan", country: "India" },
    { name: "Raurkela", state: "Odisha", country: "India" },
    { name: "Jodhpur", state: "Rajasthan", country: "India" },
    { name: "Mangalore", state: "Karnataka", country: "India" },
    { name: "Warangal", state: "Telangana", country: "India" },
    { name: "Rajkot", state: "Gujarat", country: "India" },
    { name: "Srinagar", state: "Jammu and Kashmir", country: "India" },
    { name: "Gandhinagar", state: "Gujarat", country: "India" },
    { name: "Kochi", state: "Kerala", country: "India" },
    { name: "Jammu", state: "Jammu and Kashmir", country: "India" },
    {name: "Agartala", state: "Tripura", country: "India"}
  ];
  
  export default citiesData;
  